# src/cortices/qq_chat/config/config.toml
# QQ Chat Cortex 的配置文件

# 是否启用此 Cortex
enable = true
bot_id = "352699068"

[adapter]
adapter_id = "qq_chat_adapter" # 自用 QQ 账号的适配器 ID
platform_type = "qq_napcat" # 平台类型
host = "127.0.0.1"
port = 8080

[adapter.chat]
# 黑白名单功能配置
group_list_type = "whitelist" # 可选: whitelist, blacklist
group_list = [
    728636404,
    784394807,
]

private_list_type = "blacklist" # 可选: whitelist, blacklist
private_list = []